/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Attendance;
import java.util.List;
import io.swagger.model.Schedule;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-15T18:21:33.809Z")

@Api(value = "Teacher", description = "the Teacher API")
public interface TeacherApi {

    @ApiOperation(value = "Get Schedule for teacher", nickname = "getSchedule", notes = "", response = Schedule.class, tags={ "Teacher", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Schedule.class),
        @ApiResponse(code = 400, message = "Invalid username supplied"),
        @ApiResponse(code = 404, message = "User not found") })
    @RequestMapping(value = "/Teacher/getSchedule{username}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Schedule> getSchedule(@ApiParam(value = "Fetch the schedule for Teacher",required=true) @PathVariable("username") String username);


    @ApiOperation(value = "Mark Attendance", nickname = "markAttendance", notes = "Mark Attendance of students", tags={ "Teacher", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid user supplied"),
        @ApiResponse(code = 404, message = "User not found") })
    @RequestMapping(value = "/Teacher/MarkAttendance",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Void> markAttendance(@ApiParam(value = "List of Attendance object" ,required=true )  @Valid @RequestBody List<Attendance> body);

}
